language: java
sudo: false
before_install:
- cd etc/build
script: ant war
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: GXBNXmcvhDQnb8XIHT33AceEU7uNIThTltfYI2Tf3dyLtdN29hPaRqtveJRQ84Mj5we/WvgaRR2FP92ESLGzpSwV4fHaOGlI2acau3x30Z0VSh4v4YLV/D4tETR3ngOCG5e7jSsX02FNsd9Zu7NbPOdYqPF4Tjw5yy+xRwsBKKZ0jitHORyRME6FVtMOoclaMzTh+h0/ifIo1GgZJHZgIGxsWMR9zYbwLcZm6HuzCn03YVTuQYvxwtopNkr4v0I2tPf3QOzH/Wkr1ra98hT2DYtK2wxR1dWLepNB7PSAE5zu5eCz4Rp7GDS1azR49abVscQcZJumoMnJqnn3jHc7KtCFSlygkIDOK6AZrNmbkWaHbCcwFEVRGcydqbVoySBCpfAWvNu5jQ1x91/FTh/5Z/0dSdJ1CdrCpJ/T58FiX9IzRXJlRu0Sh4XrItrUCBx+06NWAFThhJJilRDSn0jq5fGcUJgqUxbJBXZuIIvfAV0oUph3hU68WFJzPYQEiIDomCexc+vz5iubRnZZKVPk0I3dAd97jrP29vpj+EnBKy1HbiGuqE1TZpnLA9Xk9KA2yzhfmLLbW7sKUwz8oELKCjVJvzO52hMkaat3jdRnJwsf6YEohX6INZ7A2zPiyh1sJf2yVx7mCnn7aQb8ZDw6ReSjDPUDAdjxvQQ1YHs+CIU=
  file: build/draw.war
  skip_cleanup: true
  on:
    repo: jgraph/drawio
    tags: true
